name: trivia_app
description: A simple MVP quiz app to test the capabilities of Cardoteka
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  http: 1.0.0
  json_annotation: 4.8.1
  freezed_annotation: any
  html_unescape: ^2.0.0

  cardoteka:
    path: ../../cardoteka

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 2.1.2
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  freezed: ^2.3.4
  json_serializable: any
  build_runner: any

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

