name: trivia_app
description: >-
  A simple MVP quiz app to test the capabilities of Cardoteka.
  Enjoy solving quizzes and viewing statistics.
  That's all there is to it.
publish_to: 'none'
repository: https://github.com/PackRuble/trivia_app
homepage: https://t.me/+AkGV73kZi_Q1YTMy
topics:
  - cardoteka
  - trivia
  - quiz

version: 1.0.2+3

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cardoteka: # todo change
    path: ../../cardoteka

  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  weather_animation: 0.0.2
  confetti:
    git:
      ref: b490910
      url: https://github.com/funwithflutter/flutter_confetti.git
  json_annotation: 4.8.1
  freezed_annotation: 2.2.0
  html_unescape: ^2.0.0
  simple_icons: ^7.10.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.1.2
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  freezed: 2.3.5
  json_serializable: 6.7.0
  build_runner: 2.4.5

screenshots:
  - description: 'Banner'
    path: res/banner.png

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

