name: quiz_prize_app
description: >-
  A simple MVP quiz app to test the capabilities of Cardoteka.
  Enjoy solving quizzes and viewing statistics.
  That's all there is to it.
publish_to: 'none'
repository: https://github.com/PackRuble/quiz_prize_app
homepage: https://t.me/+AkGV73kZi_Q1YTMy
topics:
  - cardoteka
  - trivia
  - quiz

version: 2.0.0+5

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cardoteka: ^1.0.1

  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  http: ^1.2.1
  weather_animation: ^1.0.1
  confetti:
    git:
      ref: b490910
      url: https://github.com/funwithflutter/flutter_confetti.git
  json_annotation: 4.8.1
  freezed_annotation: ^2.4.1
  html_unescape: ^2.0.0
  simple_icons: ^10.1.3
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

screenshots:
  - description: 'Banner'
    path: res/banner.png

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

