name: trivia_app
description: A simple MVP quiz app to test the capabilities of Cardoteka
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  http: ^1.0.0
  confetti:
    git:
      ref: b490910
      url: https://github.com/funwithflutter/flutter_confetti.git
  collection: ^1.17.2
  json_annotation: 4.8.1
  freezed_annotation: 2.2.0
  html_unescape: ^2.0.0
  simple_icons: ^7.10.0
  weather_animation: 0.0.2

  cardoteka:
    path: ../../cardoteka

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 2.1.2
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  freezed: 2.3.5
  json_serializable: 6.7.0
  build_runner: 2.4.5

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

